# Generated by Django 4.2.19 on 2025-02-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='crew',
            field=models.ManyToManyField(to='station.crew'),
        ),
    ]
