# Generated by Django 4.2.19 on 2025-02-15 11:41

from django.db import migrations, models
import django.db.models.deletion
import station.models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_alter_route_destination_alter_route_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='train',
            name='crew',
        ),
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(null=True, upload_to=station.models.train_image_file_path),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='station.journey'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='station.order'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('journey', 'cargo', 'seat')},
        ),
    ]
